# Generated by Django 4.2.1 on 2023-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=10, verbose_name='測站')),
                ('publishTime', models.CharField(max_length=20, verbose_name='紀錄時間')),
                ('pm', models.CharField(max_length=10, verbose_name='PM2.5濃度')),
                ('aqi', models.CharField(max_length=10, verbose_name='AQI指數')),
                ('airQuility', models.CharField(max_length=10, verbose_name='空氣品質')),
            ],
            options={
                'db_table': 'AirData',
            },
        ),
    ]
