# Generated by Django 4.2.1 on 2023-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webClawer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdata',
            name='country',
            field=models.CharField(default='', max_length=10, verbose_name='縣市'),
            preserve_default=False,
        ),
    ]
